# Generated by Django 3.1.7 on 2021-02-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210225_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='resourceName',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='link',
            new_name='resourceUrl',
        ),
    ]
