# Generated by Django 3.1.7 on 2021-02-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210226_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resourceName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourceUrl',
            new_name='url',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
