# Generated by Django 3.1.7 on 2021-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateCreated',
            field=models.DateField(),
        ),
    ]
