# Generated by Django 3.1.7 on 2021-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210302_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
